title: More PRML Errata
description: Some more errata and additional comments for PRML
google_analytics: UA-90325348-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
  - jekyll-sitemap
